name: starthack25
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  - scipy
  - flask
  - flasgger
  - flask-cors
  - flask-sock
  - azure-cognitiveservices-speech-sdk
  - soundfile
  - librosa
  - noisereduce
  - torch
  - dotenv
  - uuid
  - pip:
    - openai
    - df
