name: starthack25_test
channels:
  # - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  # - faiss-cpu
  - pip:
    - openai
    - scipy
    - flask
    - flasgger
    - flask-cors
    - flask-sock
    - soundfile
    - librosa
    - torch --index-url https://download.pytorch.org/whl/cpu
    - torchvision --index-url https://download.pytorch.org/whl/cpu
    - torchaudio --index-url https://download.pytorch.org/whl/cpu
    - noisereduce
    # - deepfilternet
    - dotenv
    - pyannote.audio
    - openai-whisper
    - pandas
    - speechbrain
    - funasr
    - python-dotenv
    - python-ffmpeg
