name: starthack25
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - numpy
  - pandas
  - requests
  - python-dotenv
  - pytest
  - black
  - flake8
  - pip:
    - openai
    - langchain
    - poetry
